SET(OBD_SIMGEN_RANDOM "On" CACHE BOOL "Enable Random obdsim generator")

IF(OBD_SIMGEN_RANDOM)
	FILE(GLOB OBDSIMGEN_RANDOM_SRCS
		generators/random/*.c
	)
	ADD_LIBRARY(ckobdsim_random STATIC ${OBDSIMGEN_RANDOM_SRCS})
	SET(GENERATOR_LIBS ${GENERATOR_LIBS} ckobdsim_random)
	ADD_DEFINITIONS(-DOBDSIMGEN_RANDOM)
ENDIF(OBD_SIMGEN_RANDOM)

