.TH obd2kml 1
.SH NAME
obd2kml \- Convert obdgpslogger(1) logs to Google Earth kml files

.SH SYNOPSIS
.B obd2kml [ options ]

.SH DESCRIPTION
.IX Header "DESCRIPTION"
Convert obdgpslogger(1) logs to Google Earth kml files

.SH OPTIONS
.IX Header "OPTIONS"
.IP "-o|--out <output filename>"
Output to this .kml file
.IP "-a|--altitude <altitude>"
In the kml file, normalise the graph to this height
.IP "-d|--db <database>"
Work from logs stored in this database file
.IP "-n|--name <folder name>"
Everything in this output file is wrapped in a folder named this
.IP "-v|--version"
Print out version number and exit.
.IP "-h|--help"
Print out help and exit.

.SH NOT OPTIONS
.IX Header "NOT OPTIONS"
These options aren't intended for end-users, they're for the GUI.
.IP "-p|--progress"
Print out progress. It will occasionally print a number in the range 
[0..100], indicating progress percentage.
 
.SH SEE ALSO
.IX Header "SEE ALSO"
.BR "obdgpslogger(1), obd2csv(1), obd2gpx(1), obdsim(1), obdgui(1), obdlogrepair(1)"

.SH AUTHORS
Gary "Chunky Ks" Briggs <chunky@icculus.org>

