.TH obd2gpx 1
.SH NAME
obd2gpx \- Convert obdgpslogger(1) logs to gpx files

.SH SYNOPSIS
.B obd2gpx [ options ]

.SH DESCRIPTION
.IX Header "DESCRIPTION"
Convert obdgpslogger(1) logs to gpx files

.SH OPTIONS
.IX Header "OPTIONS"
.IP "-o|--out <output filename>"
Output to this .gpx file
.IP "-d|--db <database>"
Work from logs stored in this database file
.IP "-v|--version"
Print out version number and exit.
.IP "-h|--help"
Print out help and exit.
 
.SH SEE ALSO
.IX Header "SEE ALSO"
.BR "obdgpslogger(1), obd2gpx(1), obd2kml(1), obdsim(1), obdgui(1), obdlogrepair(1)"

.SH AUTHORS
Gary "Chunky Ks" Briggs <chunky@icculus.org>

